[package]
name = "send-rust-websocket"
version = "0.1.0"
authors = ["Donovan Preston <donovanpreston@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
itertools = "0.8.0"
ring = "0.13.5"
serde_json = "1.0"
websocket = "0.22.0"
